### ISSUE TITLE
ValueError: max() iterable argument is empty when using M5Stack Atom Echo with Music Assistant

### ISSUE THREAD

**Issue by szhorvath** [music-assistant/support#3637]
### What version of Music Assistant has the issue?

2.4.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Description:
When using Music Assistant Server version 2.4.2 as an add‑on in Home Assistant, I encounter the following error when attempting to play media on my M5Stack Atom Echo device:
```php
ValueError: max() iterable argument is empty
```
This error originates in the Music Assistant code (specifically in `music_assistant/controllers/streams.py`) when it calls:

```py
player_max_bit_depth = max(supported_bit_depths)
```
It appears that the list of supported bit depths is empty. Since Python’s max() function does not accept an empty iterable (unless a default is provided), the error is raised.

### How to reproduce

1. Flash the M5Stack Atom Echo with the provided ESPHome YAML (using the wake‑word voice assistant package).
2. Ensure the device connects and appears in Home Assistant as a media_player.
3. Use Music Assistant to play media on the device.
4. The Music Assistant logs display the error regarding the empty iterable when calling max() on the supported bit depths.

### Music Providers

- radio
- local file
- spotify
- audiobookshelf

### Player Providers

M5Stack Atom Echo wake‑word voice assistant

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/19018399/music-assistant.log)

### Additional information

Environment Details:

Music Assistant Server Version: 2.4.2
Home Assistant OS: Running Music Assistant as an add‑on (inside a Docker container)
Python Version: 3.12
Device: M5Stack Atom Echo (flashed with ESPHome)
ESPHome Firmware: Using the wake‑word voice assistant package from [esphome/wake-word-voice-assistants](https://github.com/esphome/wake-word-voice-assistants)

ESPHome YAML Configuration (Snippet):
```yaml
substitutions:
  name: m5stack-atom-echo
  friendly_name: M5Stack Atom Echo
  micro_wake_word_model: okay_nabu  # other options: alexa, hey_jarvis, hey_mycroft

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2025.2.0

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

# (Additional configuration omitted for brevity)
```

This firmware is compiled and flashed onto the M5Stack Atom Echo. Once connected, the device appears in Home Assistant via the ESPHome integration as a media_player entity.

Suggested Patch/Workaround:
It appears the error is due to the device not reporting any supported bit depths. One potential solution is to modify the Music Assistant code so that it uses a default value when the list is empty. For example, change:

```py
player_max_bit_depth = max(supported_bit_depths)
```
to:

```py
player_max_bit_depth = max(supported_bit_depths, default=16)

```

This would allow Music Assistant to fall back to a default bit depth (e.g., 16) when no supported bit depths are provided.

Questions for the Team:

- Is this behavior expected for devices (like the M5Stack Atom Echo) that do not advertise their supported bit depths?
- Would adding a default value in the code (as suggested) be an acceptable solution, or is there a better approach—perhaps a change needed in the ESPHome firmware to properly report supported bit depths?

I appreciate your help in resolving this issue.

### What version of Home Assistant Core are your running

2025.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
this should be fixed in the next patch release (2.4.3) - if you want to test it before that is released, check out the beta 2.5.3 later today

**Comment by OzGav** [comment]
I am still seeing the error here on 2.5.0b4

**Comment by marcelveldt** [comment]
> I am still seeing the error here on 2.5.0b4

Please let me know if the issue really still exists because I tested with 4 (!) different devices and it works.
Maybe the layer config got messed up or some outdated esphome config ?
If the issue persists I need to have exact reproduce steps, beginning with the esphome config.

**Comment by OzGav** [comment]
Entirely possible its a config issue as I just pulled this out of the drawer to test.

```
substitutions:
  name: m5stack-atom-echo-8a1cd4
  friendly_name: M5 Voice Main Bedroom
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: secret_too


wifi:
  ssid: "secret"
  password: "also secret"

  manual_ip:
    static_ip: 192.168.1.141
    gateway: 192.168.1.254
    dns1: 192.168.1.250
    dns2: 192.168.1.166
    subnet: 255.255.255.0
```

**Comment by szhorvath** [comment]
@OzGav, @marcelveldt, Thank you for your help.

Every other kind of speaker works flawlessly, but these two M5 devices throw errors for some reason. It could be a settings issue, but I'm not sure what I'm doing wrong.

 Just to be safe, I reflashed both of my devices with the latest ESPHome (2025.2.2) and I am now using Music Assistant Server 2.4.3.

I still get the same error.

```sh
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 319, in serve_queue_item_stream
    output_format = await self.get_output_format(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 1002, in get_output_format
    player_max_bit_depth = max(supported_bit_depths)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

Both of my M5s have that same config:

```yaml
substitutions:
  name: m5stack-atom-echo-a1498c
  friendly_name: Living Room M5Stack Atom Echo
  
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: secret


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

My device does not have a manual IP set, so I will try setting one; it might help. I will also experiment with some other settings. Any advice on what I should try changing would be appreciated.

Thanks

**Comment by OzGav** [comment]
[config_entry-esphome-01J50R2K73RDMTHTB1DFW2PVR3.json](https://github.com/user-attachments/files/19136587/config_entry-esphome-01J50R2K73RDMTHTB1DFW2PVR3.json)

**Comment by marcelveldt** [comment]
2.4.4 is released with a patch for this issue

**Comment by OzGav** [comment]
Unfortunately I still see the error.

**Comment by szhorvath** [comment]
I'm experiencing the same issue. The error persists despite adjusting all the dials I could find. As I'm not an expert, it might be a user error, but I'm uncertain about what to change next.

**Comment by marcelveldt** [comment]
Can you try to remove the player from MA ?
Remove it from the HA player provider and make sure that the config is also removed (there is no more entry in the config-players list).

**Comment by marcelveldt** [comment]
Can you tell me what the expectations are of the device ?
I checked that diagnostics dump and there you can spot that the device does report its suitable for music playback.
Max supported sample rate of 16000, single channel. This is fine for a announcement maybe but not for music.

Also if I remember this device correctly, it has a crappy speaker.

So what are the expectations ?

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/b3e977c1-0a07-4276-ac03-8cd0f1ce9f60" />

**Comment by OzGav** [comment]
Further testing suggests this device can't be made to work. It also doesn't fit within the scope of MA to provide high quality audio. In a future update these devices will be filtered out and thus won't be able to be added to MA.

**Comment by szhorvath** [comment]
> Further testing suggests this device can't be made to work. It also doesn't fit within the scope of MA to provide high quality audio. In a future update these devices will be filtered out and thus won't be able to be added to MA.

Fair enough. The speaker's quality is not great; I primarily used it for radio talks and podcasts. Thank you for the help guys. 

@OzGav, @marcelveldt, The music assistant is fantastic, and I appreciate your hard work. Thank you!

**Comment by mikey0000** [comment]
This is also a problem with the new respeaker from seed studio (really disappointed), would be good to have a proper error displayed that the device is not supported.
