### ISSUE TITLE
Audible: MultiPartBooks not working

### ISSUE THREAD

**Issue by andreasziegl** [music-assistant/support#3880]
### What version of Music Assistant has the issue?

2.5.1 HASSIO addon

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Hi, 
first thank you for all the effort you are putting in this. It is really amazing!!

Unfortunately i am facing an issue with Audible. When I am syncing my lib, it only lists a fraction of my audiobooks. All others are failing with this error:

2025-04-15 16:02:32.292 DEBUG (MainThread) [music_assistant.audible] Skipping non-audiobook item: Das blutige Land (MultiPartBook)

All the best
Andreas

### How to reproduce

Have a MultiPart audio book

### Music Providers

Audible

### Player Providers

Airplay

### Full log output

[d5369777_music_assistant_2025-04-15T14-10-31.175Z.log.zip](https://github.com/user-attachments/files/19759741/d5369777_music_assistant_2025-04-15T14-10-31.175Z.log.zip)

### Additional information

Nothing more

### What version of Home Assistant Core are your running

2025.4.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by Daverover66** [comment]
Not sure if this is a related issue but it is similar.

I'm running:
HAOS 2025.4.0
OS 15.1
Supervisor 2025.04.0

Music Assistant 2.5.1

Home Assistant is on a Beelink S12Pro N100 mini pc.

When I sync my Audible library, I get this in the logs:

```
2025-04-19 12:47:14.532 INFO (MainThread) [music_assistant.audible] Audible: Successfully retrieved 413 audiobooks from library
```
No errors, but the folder `Browse | Audible://` shows 166 books.

**Comment by OzGav** [comment]
This should be fixed in the beta so please try that. You can run it in parallel with your main instance just don't have them both running at the same time. https://www.music-assistant.io/release/#running-parallel-server-versions

**Comment by OzGav** [comment]
@andreasziegl Please advise if you can try the beta

**Comment by andreasziegl** [comment]
@OzGav thank you for checking! I will try next week and come back to you

**Comment by andreasziegl** [comment]
@OzGav  I tried with  2.6.0b3, unfortunately the issue is still there. 

[d5369777_music_assistant_beta_2025-04-21T10-29-19.688Z.log.zip](https://github.com/user-attachments/files/19832889/d5369777_music_assistant_beta_2025-04-21T10-29-19.688Z.log.zip)

**Comment by OzGav** [comment]
@ztripez

**Comment by ztripez** [comment]
The problem is multipart books;I don't have any myself, so I can't reverse-engineer the API to get the stream URLs and licenses for them. I'll try to find and buy a book that's in multiple parts.

**Comment by andreasziegl** [comment]
@ztripez would be more than happy to sponsor one for you

**Comment by ztripez** [comment]
> [@ztripez](https://github.com/ztripez) I would be more than happy to sponsor one for you

Thanks, not needed but I do have a buy me a coffee link in my profile :). 
I'm a little overloaded on my day job this week but i hope i can take a dive into it this weekend.
